### ISSUE TITLE
Alacritty terminal theme support

### ISSUE THREAD

**Issue by PezCoder** [AlexvZyl/nordic.nvim#78]
First off, beautiful theme! I'm coming from using Gruvebox & wanting to change it for a while, this gives a great fresh vibe & similar soothing color pallets 🌈 

I use [Alacritty](https://github.com/alacritty/alacritty) as my terminal & ended up porting the theme using 🤖 chatgpt by inputting [iterm2 nordic theme](https://github.com/AlexvZyl/nordic.nvim/blob/main/platforms/iTerm2/nordic.itermcolors)

This is what it gave me & with minor tweaks to selection colors, it looks pretty decent.

```yml
colors:
  # Default colors
  primary:
    background: '#242626'
    foreground: '#BBBDAF'

  # Normal colors
  normal:
    black: '#191C1D'
    red: '#BD6062'
    green: '#A3D6A9'
    yellow: '#F0DFAF'
    blue: '#8FB4D8'
    magenta: '#C7A9D9'
    cyan: '#B6D7A8'
    white: '#BDC5BD'

  # Bright colors
  bright:
    black: '#727C7C'
    red: '#D18FAF'
    green: '#B7CEB0'
    yellow: '#BCBCBC'
    blue: '#E0CF9F'
    magenta: '#C7A9D9'
    cyan: '#BBDA97'
    white: '#BDC5BD'


  # Selection color
  selection:
    text: '#000000'
    background: '#F0DFAF'
```

I'll wait for an "official" port to arrive, but meanwhile, others can use this as an alternative.
